### ISSUE TITLE
bug list

### ISSUE THREAD

**Issue by ddkwork** [wcharczuk/json2go#1]

**Comment by ddkwork** [comment]
https://github.com/baidu/amis/releases/tag/6.7.0

scheme.json

**Comment by wcharczuk** [comment]
thanks for the bug report! should be fixed in HEAD

**Comment by ddkwork** [comment]
![Screenshot_20240822_141430_com.realvnc.viewer.android.jpg](https://github.com/user-attachments/assets/5c879522-89e5-476c-8c36-d9897f137ca6)

Repeated fields

**Comment by ddkwork** [comment]
I added a test and it does have two id fields, so should we populate the tag with the original name while renaming the field? i think so, not sure

https://github.com/ddkwork/json2go/blob/main/main.go#L169-L173

https://github.com/ddkwork/json2go/blob/main/main_test.go#L14-L26

**Comment by ddkwork** [comment]
![Screenshot_20240822_212948_com.realvnc.viewer.android.jpg](https://github.com/user-attachments/assets/7b251659-226e-4fb8-a8f3-dc5ad89aae4c)

```go
"AjaxActionSchema": {
      "type": "object",
      "properties": {
        "$$id": {
          "type": "string",
          "description": "组件唯一 id，主要用于页面设计器中定位 json 节点"
        },
        "className": {
          "$ref": "#/definitions/SchemaClassName",
          "description": "容器 css 类名"
        },
        "$ref": {
          "type": "string",
          "description": "配合 definitions 一起使用，可以实现无限循环的渲染器。"
        },
        "disabled": {
          "type": "boolean",
          "description": "是否禁用"
        },
        "disabledOn": {
          "$ref": "#/definitions/SchemaExpression",
          "description": "是否禁用表达式"
        },
        "hidden": {
          "type": "boolean",
          "description": "是否隐藏"
        },
        "hiddenOn": {
          "$ref": "#/definitions/SchemaExpression",
          "description": "是否隐藏表达式"
        },
        "visible": {
          "type": "boolean",
          "description": "是否显示"
        },
        "visibleOn": {
          "$ref": "#/definitions/SchemaExpression",
          "description": "是否显示表达式"
        },
        "id": {
          "type": "string",
          "description": "主要用于用户行为跟踪里区分是哪个按钮"
        },
        "onEvent": {
          "type": "object",

```

```go
"$$id": {
          "type": "string",
          "description": "组件唯一 id，主要用于页面设计器中定位 json 节点"
        },

Ps

"id": {
          "type": "string",
          "description": "主要用于用户行为跟踪里区分是哪个按钮"
        },

```
They has the same name

**Comment by wcharczuk** [comment]
yeah it's because we have to escape the `$$` (which is not valid for go field names), lemme have a think how to work around this

**Comment by wcharczuk** [comment]
the `id` vs. `$$id` issue should be fixed

**Comment by ddkwork** [comment]
still not working, let me check it.

**Comment by ddkwork** [comment]
![image](https://github.com/user-attachments/assets/dbdc6114-88af-4872-922d-5d894453d552)

**Comment by ddkwork** [comment]
![image](https://github.com/user-attachments/assets/82a2a9f2-205b-41de-9d93-8cf13f831b8d)

**Comment by ddkwork** [comment]
Additionally, to keep the original field order, we can remove the field ordering and replace this with this package

https://github.com/trichner/toolbox/blob/main/pkg/jsontree/parser.go


```go
	data, err := io.ReadAll(bytes.NewReader(schema))
	maybeFatal(err)

	var obj any
	err = json.Unmarshal(data, &obj)
	maybeFatal(err)

	typeMeta := anyToType(obj)
```

**Comment by ddkwork** [comment]
last bug
![image](https://github.com/user-attachments/assets/279035f6-e1ef-41b9-b2f2-a316174f9471)
![image](https://github.com/user-attachments/assets/115c954f-2bfd-489b-a436-427e9b937db1)

**Comment by wcharczuk** [comment]
`$$` should be fixed

**Comment by wcharczuk** [comment]
the `array` issue just lifting to string (instead of boolean) should be fixed as well

**Comment by wcharczuk** [comment]
for the field order, i'd really like to keep this zero dependency if possible, so i'll likely not add a 3rd party lib for the json structure parser. that would be a better way to build this though!

**Comment by ddkwork** [comment]
> for the field order, i'd really like to keep this zero dependency if possible, so i'll likely not add a 3rd party lib for the json structure parser. that would be a better way to build this though!

Another way is to modify the standard library's json decoding library to return the original order of the map, this is also troublesome, but I would like to try to make a library like this, maybe other projects will use it.

**Comment by ddkwork** [comment]
> `$$` should be fixed

![image](https://github.com/user-attachments/assets/1cc9b00d-b4f9-4cda-b50b-c6143ec2c370)

https://github.com/ddkwork/json2go/blob/main/main.go#L208-#L234
